name: Broken link checker

on:
  schedule:
    - cron: '0 5 * * 1-5'
  workflow_dispatch:
    inputs: { url: { description: 'URL to check', required: false, default: 'https://es-toolkit.dev' } }

jobs:
  broken-link-checker:
    if: github.repository == 'toss/es-toolkit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v5
        with:
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
          node-version-file: '.nvmrc'
      - run: yarn install
      - name: Check broken link
        env:
          url: ${{ github.event.inputs.url || 'https://es-toolkit.dev' }}
        run: yarn blc $url --ro
